Up Files

diff --git a/Setup_JiuWei b/Setup_JiuWei
--- a/Setup_JiuWei
+++ b/Setup_JiuWei
@@ -229,9 +229,17 @@ update_run
 check_code
 
 mkdir -p "$MAIN_DIR" "$BIN" "$CACHE" "$FOXINDEX"
-echo "#Jiuwei repository" > "$CONFIG"
-echo "SOURCE=\"https://gitee.com/CNTangyuan/JiuWei-repository/raw/master\"" >> "$CONFIG"
+if ! wget -O "$CONFIG" "https://gitee.com/CNTangyuan/JiuWei/raw/master/config.list"; then
+    echo -e "${COLOR_RED}[ERROR] An error occurred while downloading...Exit.${COLOR_DEFAULT}"
+    exit 1
+fi
 touch "$HBI"
+
+if ! wget -O "$MAIN_DIR/CHANGE.log" "https://gitee.com/CNTangyuan/JiuWei/raw/master/CHANGE.log"; then
+    echo -e "${COLOR_RED}[ERROR] An error occurred while downloading...Exit.${COLOR_DEFAULT}"
+    exit 1
+fi
+
 cd "$BIN"
 
 # 使用wget命令从指定URL下载文件
